name: fisspy
channels:
    - astropy
    - conda-forge
    - albop
dependencies:
- astropy
- cython
- matplotlib
- astropy-helpers
- numpy
- patsy
- pillow
- python=3.6*
- scipy
- scikit-image
- suds-jurko
- wcsaxes
- numba
- interpolation
- pillow
- pip:
    - sphinx-gallery
    - glymur
